"""Add votes field to Candidate model

Revision ID: 548def8afb95
Revises: d4692fa9cab0
Create Date: 2025-01-04 02:55:53.490113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548def8afb95'
down_revision = 'd4692fa9cab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
