"""Add voting time table config

Revision ID: 56ace951d270
Revises: cf7588723c7f
Create Date: 2025-01-04 17:17:44.417210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ace951d270'
down_revision = 'cf7588723c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_time')
    # ### end Alembic commands ###
